name: GitHub metrics
on:
  schedule: [{cron: "0 * * * *"}]
  push:
    branches: "main"
jobs:

  github-metrics-personal:
    runs-on: ubuntu-latest
    steps:
  
      - name: Personal metrics
        uses: pranavelric/metrics@master
        with:
          filename: mmetrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
       
          base: "header, activity, community, repositories"
          plugin_introduction: yes
          plugin_introduction_title: yes
          plugin_lines: yes
          plugin_music: no
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_topics: yes
          plugin_topics_sort: random
          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          config_timezone: Asia/Kolkata
          plugin_stars: yes
          plugin_stars_limit: 4
          plugin_stargazers: yes
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 14
          plugin_people: yes
          plugin_people_types: followers, following
          plugin_people_limit: 200
          plugin_people_size: 28
          repositories_forks: yes
          plugin_skyline: yes
          plugin_skyline_year: 2021
          plugin_skyline_frames: 120
          plugin_reactions: yes
          plugin_reactions_limit: 200
          plugin_reactions_days: 14
          plugin_reactions_details: percentage
          plugin_achievements: yes
          plugin_achievements_threshold: C       
          plugin_achievements_secrets: yes   
          plugin_achievements_limit: 0
          plugin_achievements_display: detailed 
          plugin_notable: yes
          plugin_support: yes
          plugin_stackoverflow: yes
          plugin_stackoverflow_limit: 1
          plugin_stackoverflow_lines: 0
          plugin_stackoverflow_lines_snippet: 0
          plugin_stackoverflow_sections: answers
          plugin_stackoverflow_user: 10224590

          
      - name: Personal metrics (detailed)
        uses: pranavelric/metrics@master
        with:
          filename: metrics.detailed.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: "metadata"
          plugin_gists: yes
          plugin_pagespeed: yes
          plugin_pagespeed_detailed: yes
          plugin_followup: yes
          plugin_followup_sections: user
          plugin_languages: yes
          plugin_pagespeed_screenshot: yes
          plugin_posts: yes
          plugin_posts_source: dev.to
          config_timezone: Asia/Kolkata
          plugin_languages_colors : "rainbow"
          plugin_languages_details: bytes-size, percentage
